### ISSUE TITLE
Implementar Backend con Enfoque API REST

### ISSUE THREAD

**Issue by MarbiFox** [benjadiazu/ICI4247-1-Proyecto#17]
Crear y codificar los scripts/archivos del Backend de la aplicación, para poder recibir las instrucciones del frontend y conectarse con la base de datos. Utilizar enfoque API REST. Se utilizará Flask para trabajar con Python.

Tareas a realizar:
- Crear directorio de Backend.
- Implementar un archivo api.py para implementar 2 consultas HTTP (GET, POST, PUT y DELETE).
- Implementar un archivo apiDB.py para conectarse mediante consultas SQL a la base de datos.
- Organizar los archivos de la carpeta de Backend.

**Comment by MarbleMenti-PUCV** [comment]
Backend de Web inicial terminado, para evaluar se debe conectar con front.
