### ISSUE TITLE
Implementar 4 Aspectos de Seguridad

### ISSUE THREAD

**Issue by MarbiFox** [benjadiazu/ICI4247-1-Proyecto#19]
Implementar aspectos de Seguridad dentro del Frontend/Backend/Base de Datos.

Tareas a realizar:
- Utilizar JWT (JSON Web Token) para la autenticación y autorización (Frontend).
- Encriptar contraseñas utilizando bcript (Python) en el Backend.
- Modificar los permisos de la base de datos, especificando el usuario y contraseña de acceso en el Backend.
- Definir un 4° aspecto de seguridad.
- Aplicar un 4° aspecto de seguridad.

**Comment by MarbleMenti-PUCV** [comment]
Actualización (Backend):

> API REST necesita de la validación de una JWT. (Falta trabajar el Front).
> Base de Datos tiene permisos de usuario y admin distintos.
> API REST encripta la contraseña recibida del Front para guardarla en la base de datos.

**Comment by MarbleMenti-PUCV** [comment]
Validación de JWT en Backend terminada. Falta operar JWT en Front.
